### PR TITLE
Refactored

### PR DESCRIPTION
**Pull request by Kovarthanan-murugan**
1. In class ModedDesktopInput 
      In  Update method
           Refactored the complex conditional
2. In Class ModedDesktopInput
     In Update method
       Introduced Explaining Variable
     In Class ModedGlyphLayout
     In setText method
     Introduced Explaining Variable

3. In Class ModedMobileInput
     In Update method
         Refactored the complex update method

4. In Class Darkdusty and SlashJs
    have a duplicate method so pull up the method to class AdminsTools.
    and override the same method in the internal class which has a different implementation compared.
    to other two classes which implement the same class.

5. Refactored Cyclic Dependency
     Classes FlipButton and HudFragments were implemented with cyclic dependency.
     Made changes to refactor the cyclic dependency.

6. Refactored Conditional Statement with polymorphism
   In BuildsCache class refactored the cache method so new conditions can be added.

### CODE REVIEW

**Comment by xzxADIxzx** [comment]
000fe2f4d50668f2eb2ed46502bd6b1f47d21d54
image

Do you create cache objects every time a building is cached, but don't store them anywhere?
And don't use List, Anuken/Arc has a Seq class which is a bit faster

**Comment by xzxADIxzx** [comment]
000fe2f4d50668f2eb2ed46502bd6b1f47d21d54
image

And why are there two spaces? ;-;

**Review by xzxADIxzx — APPROVED** [review]
6c79c9d5b0b218de53ae0bbe293a4120fb938861 is good

**Comment by xzxADIxzx** [comment]
6bce30ac3c19572a38ebd357e79658cecd0fff1d
image

Why did you copy the send method into AdminsTools?

**Comment by xzxADIxzx** [comment]
e21c0fd5627fc3a80867c59d63b5a754ee1fecdc
image

The first two lines say `mouseX - screenWidth` and `mouseY - screenHeight`, but you only have the first of the two, so the camera will only move diagonally from bottom left to top right ;-;

**Comment by xzxADIxzx** [comment]
831106e0485331bcd14f03224b0e313be53fc4d7 is good

**Comment by Kovarthanan-murugan** [comment]
> [e21c0fd](https://github.com/xzxADIxzx/Scheme-Size/commit/e21c0fd5627fc3a80867c59d63b5a754ee1fecdc) image

> The first two lines say `mouseX - screenWidth` and `mouseY - screenHeight`, but you only have the first of the two, so the camera will only move diagonally from bottom left to top right ;-;

I appreciate you taking the time to review my modifications and provided feedback for my changes. I have rectified the error you pointed out.

b50495d
image

**Comment by Kovarthanan-murugan** [comment]
> [6bce30a](https://github.com/xzxADIxzx/Scheme-Size/commit/6bce30ac3c19572a38ebd357e79658cecd0fff1d) image
> 
> Why did you copy the send method into AdminsTools?

It should not be there, I added it by mistake, fixed it in 
0548fbc

**Comment by Kovarthanan-murugan** [comment]
> [000fe2f](https://github.com/xzxADIxzx/Scheme-Size/commit/000fe2f4d50668f2eb2ed46502bd6b1f47d21d54) image
> 
> And why are there two spaces? ;-;

Fixed it in 
0548fbc

**Pull request closed without merging**
