### PR TITLE
Uh.. yeah.

### PR DESCRIPTION
**Pull request by SMOLKEYS**
Fixes up some english issues.

~~And if you don't mind me asking, can you help me (UI) with my [mod](https://github.com/SMOLKEYS/yellow-java)?~~

### CODE REVIEW

**Comment by xzxADIxzx** [comment]
You forgot to change "mod" to "Scheme Size" on line 96... And I suspect that I will have to change the translation to other languages

**Comment by xzxADIxzx** [comment]
Yeah, I can help you with ui... but what exactly do you need?

**Comment by SMOLKEYS** [comment]
> Yeah, I can help you with ui... but what exactly do you need?

Basically, i'm trying to make a [button](https://github.com/SMOLKEYS/yellow-java/blob/master/src/yellow/ui/buttons/YellowWeaponSwitch.java) that opens [this dialog](https://github.com/SMOLKEYS/yellow-java/blob/master/src/yellow/ui/buttons/dialogs/YellowWeaponSwitchDialog.java) here.

The button part is my issue, i'm batshit with java UI.
Can you help me with that?

**Comment by xzxADIxzx** [comment]
image
something like this?

**Comment by xzxADIxzx** [comment]
image
what is that?

**Comment by SMOLKEYS** [comment]
> image something like this?

The B3 part

**Comment by SMOLKEYS** [comment]
> image what is that?

Github Actions, it autocompiles the mod every commit and can let you know if it compiled or not.

If not, there's an issue.

**Comment by xzxADIxzx** [comment]
> Github Actions, it autocompiles the mod every commit and can let you know if it compiled or not.
> 
> If not, there's an issue.

Ok... but which phantom updates? I have never seen such

**Comment by SMOLKEYS** [comment]
> > Github Actions, it autocompiles the mod every commit and can let you know if it compiled or not.
> > If not, there's an issue.
> 
> Ok... but which phantom updates? I have never seen such

Basically:

The latest version of a mod is v1.3, but the latest *release* is v1.1

And if you have v1.3 installed, the autoupdater assumes your mod version is outdated, notifying you.

**Comment by SMOLKEYS** [comment]
@xzxADIxzx and about the UI thing... can you help me with it?

**Comment by xzxADIxzx** [comment]
oh? ofcourse

**Comment by xzxADIxzx** [comment]
and can you tell my... **why 400kb?!**
image

**Comment by xzxADIxzx** [comment]
say something about this... maybe I need to correct something?
image

**Comment by SMOLKEYS** [comment]
> say something about this... maybe I need to correct something? image

No need, that's good.

**Pull request merged**
